services: 
  distributed-faas-kafka-broker-1:
    container_name: distributed-faas-kafka-broker-1
    image: confluentinc/cp-kafka:${KAFKA_VERSION-7.2.5}
    ports:
      - "19092:19092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: distributed-faas-zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://:9092,EXTERNAL://:19092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://distributed-faas-kafka-broker-1:9092,EXTERNAL://localhost:19092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - "./volumes/kafka/broker-1:/var/lib/kafka/data"
    networks:
      - ${GLOBAL_NETWORK:-distributed-faas}
    profiles:
      - test-create-invocation
      - test-create-user
      - test-create-charge
      - test-calculate-billing
      - test-generate-billing

  distributed-faas-kafka-dlq-1:
    container_name: distributed-faas-kafka-dlq-1
    image: confluentinc/cp-kafka:${KAFKA_VERSION-7.2.5}
    hostname: kafka-dlq-1
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: distributed-faas-zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://:9092,EXTERNAL://:29092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://distributed-faas-kafka-dlq-1:9092,EXTERNAL://localhost:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - "./volumes/kafka/dlq-1:/var/lib/kafka/data"
    networks:
      - ${GLOBAL_NETWORK:-distributed-faas}
    profiles:
      - test-create-invocation
      - test-create-user
      - test-create-charge
      - test-calculate-billing
      - test-generate-billing

  distributed-faas-debezium-connect:
    container_name: distributed-faas-debezium-connect
    image: debezium/connect:2.7.3.Final
    hostname: kafka-debezium-connect
    ports:
      - 8083:8083
    depends_on:
      - distributed-faas-kafka-broker-1
    environment:
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: "connect-config"
      OFFSET_STORAGE_TOPIC: "connect-offsets"
      BOOTSTRAP_SERVERS: distributed-faas-kafka-broker-1:9092
    volumes:
      - "/mnt/d/volumes/debezium/filter-smt:/kafka/connect/debezium-connector-mongodb/filter-smt"
    networks:
      - ${GLOBAL_NETWORK:-distributed-faas}
    profiles:
      - test-create-invocation
      - test-create-user
      - test-generate-billing