up-mongo:
	@echo "Running docker-compose up for mongo..."
	docker-compose -f common.yml -f mongo.yml up -d
	@echo "docker-compose up for mongo complete."

down-mongo:
	@echo "Running docker-compose down for mongo..."
	docker-compose -f common.yml -f mongo.yml down
	@echo "docker-compose down for mongo complete."