services:
  distributed-faas-function-service:
    container_name: distributed-faas-function-service
    build:
      context: ../../../
      dockerfile: services/function-service/Dockerfile
    ports:
      - 50050:50050
    environment:
      PORT: 50050
      FUNCTION_MONGO_URI: mongodb://admin:password@distributed-faas-mongo:27017/?replicaSet=rs0&directConnection=true
      FUNCTION_MONGO_DATABASE: invocation-db
      FUNCTION_MONGO_COLLECTION: function
    networks:
      - ${GLOBAL_NETWORK:-distributed-faas} 
    restart: always
    profiles:
      - test-create-invocation

  distributed-faas-invocation-service:
    container_name: distributed-faas-invocation-service
    build:
      context: ../../../
      dockerfile: services/invocation-service/Dockerfile
    ports:
      - 50051:50050
    environment:
      PORT: 50050
      INVOCATION_MONGO_URI: mongodb://admin:password@distributed-faas-mongo:27017/?replicaSet=rs0&directConnection=true
      INVOCATION_MONGO_DATABASE: invocation-db
      INVOCATION_MONGO_COLLECTION: invocation
      FUNCTION_MONGO_URI: mongodb://admin:password@distributed-faas-mongo:27017/?replicaSet=rs0&directConnection=true
      FUNCTION_MONGO_DATABASE: invocation-db
      FUNCTION_MONGO_COLLECTION: function
    networks:
      - ${GLOBAL_NETWORK:-distributed-faas} 
    restart: always
    profiles:
      - test-create-invocation

  distributed-faas-dispatcher-service:
    container_name: distributed-faas-dispatcher-service
    build:
      context: ../../../
      dockerfile: services/dispatcher-service/Dockerfile
    environment:
      MACHINE_MONGO_URI: mongodb://admin:password@distributed-faas-mongo:27017/?replicaSet=rs0&directConnection=true
      MACHINE_MONGO_DATABASE: machine-db
      MACHINE_MONGO_COLLECTION: machine
      INVOCATION_KAFKA_BOOTSTRAP_SERVERS: distributed-faas-kafka-broker-1:9092
      INVOCATION_KAFKA_TOPIC: cdc.invocation-db.invocation
      INVOCATION_KAFKA_GROUP_ID: group-1
    networks:
      - ${GLOBAL_NETWORK:-distributed-faas}
    restart: always
    profiles:
      - test-create-invocation

  distributed-faas-machine:
    container_name: distributed-faas-machine
    build:
      context: ../../../
      dockerfile: services/machine/Dockerfile
    ports:
      - 50052:50050
    environment:
      PORT: 50050
      CHECKPOINT_MONGO_URI: mongodb://admin:password@distributed-faas-mongo:27017/?replicaSet=rs0&directConnection=true
      CHECKPOINT_MONGO_DATABASE: checkpoint-db
      CHECKPOINT_MONGO_COLLECTION: checkpoint
      OUTPUT_CLOUDFLARE_ACCOUNT_ID: 2ded753162d6aa36d6eaea983f56951d
      OUTPUT_CLOUDFLARE_ACCESS_KEY_ID: c58a8f8a5bb3ba00f5cd62325aac82e1
      OUTPUT_CLOUDFLARE_SECRET_ACCESS_KEY: 048eac9dc84455b4d405043107be51310739a39890b4c295a6650bf16cab5301
      OUTPUT_CLOUDFLARE_BUCKET_NAME: distributed-faas
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - ${GLOBAL_NETWORK:-distributed-faas}
    restart: always
    profiles:
      - test-create-invocation
  
  distributed-faas-checkpoint-processor:
    container_name: distributed-faas-checkpoint-processor
    build:
      context: ../../../
      dockerfile: services/checkpoint-processor/Dockerfile
    environment:
      INVOCATION_MONGO_URI: mongodb://admin:password@distributed-faas-mongo:27017/?replicaSet=rs0&directConnection=true
      INVOCATION_MONGO_DATABASE: invocation-db
      INVOCATION_MONGO_COLLECTION: invocation
      CHECKPOINT_KAFKA_BOOTSTRAP_SERVERS: distributed-faas-kafka-broker-1:9092
      CHECKPOINT_KAFKA_TOPIC: cdc.checkpoint-db.checkpoint
      CHECKPOINT_KAFKA_GROUP_ID: group-1
    networks:
      - ${GLOBAL_NETWORK:-distributed-faas}
    restart: always
    profiles:
      - test-create-invocation

  distributed-faas-registrar-service:
    container_name: distributed-faas-registrar-service
    build:
      context: ../../../
      dockerfile: services/registrar-service/Dockerfile
    ports:
      - 50053:50050
    environment:
      PORT: 50050
      MACHINE_MONGO_URI: mongodb://admin:password@distributed-faas-mongo:27017/?replicaSet=rs0&directConnection=true
      MACHINE_MONGO_DATABASE: machine-db
      MACHINE_MONGO_COLLECTION: machine
    networks:
      - ${GLOBAL_NETWORK:-distributed-faas} 
    restart: always
    profiles:
      - test-create-invocation

  distributed-faas-retry-service:
    container_name: distributed-faas-retry-service
    build:
      context: ../../../
      dockerfile: services/retry-service/Dockerfile
    environment:
      CHECKPOINT_MONGO_URI: mongodb://admin:password@distributed-faas-mongo:27017/?replicaSet=rs0&directConnection=true
      CHECKPOINT_MONGO_DATABASE: checkpoint-db
      CHECKPOINT_MONGO_COLLECTION: checkpoint
      RETRY_INTERVAL_IN_SEC: 10
      THRESHOLD_IN_SEC: 300
    networks:
      - ${GLOBAL_NETWORK:-distributed-faas} 
    restart: always
    profiles:
      - test-create-invocation

  distributed-faas-user-service:
    container_name: distributed-faas-user-service
    build:
      context: ../../../
      dockerfile: services/user-service/Dockerfile
    ports:
      - 50054:50050
    environment:
      PORT: 50050
      USER_MONGO_URI: mongodb://admin:password@distributed-faas-mongo:27017/?replicaSet=rs0&directConnection=true
      USER_MONGO_DATABASE: user-db
      USER_MONGO_COLLECTION: user
    networks:
      - ${GLOBAL_NETWORK:-distributed-faas} 
    restart: always
    profiles:
      - test-create-user

  distributed-faas-user-processor:
    container_name: distributed-faas-user-processor
    build:
      context: ../../../
      dockerfile: services/user-processor/Dockerfile
    environment:
      CRON_MONGO_URI: mongodb://admin:password@distributed-faas-mongo:27017/?replicaSet=rs0&directConnection=true
      CRON_MONGO_DATABASE: cron-db
      CRON_MONGO_COLLECTION: cron
      USER_KAFKA_BOOTSTRAP_SERVERS: distributed-faas-kafka-broker-1:9092
      USER_KAFKA_TOPIC: cdc.user-db.user
      USER_KAFKA_GROUP_ID: group-1
    networks:
      - ${GLOBAL_NETWORK:-distributed-faas}
    restart: always
    profiles:
      - test-create-user

  distributed-faas-charge-service:
    container_name: distributed-faas-charge-service
    build:
      context: ../../../
      dockerfile: services/charge-service/Dockerfile
    ports:
      - 50055:50050
    environment:
      PORT: 50050
      CHARGE_KAFKA_BOOTSTRAP_SERVERS: distributed-faas-kafka-broker-1:9092
      CHARGE_KAFKA_TOPIC: charge
    networks:
      - ${GLOBAL_NETWORK:-distributed-faas}
    restart: always
    profiles:
      - test-create-charge

  distributed-faas-accumulator-service:
    container_name: distributed-faas-accumulator-service
    build:
      context: ../../../
      dockerfile: services/accumulator-service/Dockerfile
    environment:
      CHARGE_MONGO_URI: mongodb://admin:password@distributed-faas-mongo:27017/?replicaSet=rs0&directConnection=true
      CHARGE_MONGO_DATABASE: charge-db
      CHARGE_MONGO_COLLECTION: charge
      CHARGE_KAFKA_BOOTSTRAP_SERVERS: distributed-faas-kafka-broker-1:9092
      CHARGE_KAFKA_TOPIC: charge
      CHARGE_KAFKA_GROUP_ID: group-1
      CHARGE_KAFKA_POLL_DURATION_SEC: 5
      CHARGE_KAFKA_MAX_BATCH_SIZE: 4
    networks:
      - ${GLOBAL_NETWORK:-distributed-faas}
    restart: always
    profiles:
      - test-create-charge

  distributed-faas-billing-calculator-service:
    container_name: distributed-faas-billing-calculator-service
    build:
      context: ../../../
      dockerfile: services/billing-calculator-service/Dockerfile
    environment:
      BILLING_MONGO_URI: mongodb://admin:password@distributed-faas-mongo:27017/?replicaSet=rs0&directConnection=true
      BILLING_MONGO_DATABASE: billing-db
      BILLING_MONGO_COLLECTION: billing
      CHARGE_MONGO_URI: mongodb://admin:password@distributed-faas-mongo:27017/?replicaSet=rs0&directConnection=true
      CHARGE_MONGO_DATABASE: charge-db
      CHARGE_MONGO_COLLECTION: charge
      CRON_KAFKA_BOOTSTRAP_SERVERS: distributed-faas-kafka-broker-1:9092
      CRON_KAFKA_TOPIC: cron
      CRON_KAFKA_GROUP_ID: group-1
      CRON_KAFKA_POLL_TIMEOUT: 5
      CRON_KAFKA_NUM_WORKERS: 3
    networks:
      - ${GLOBAL_NETWORK:-distributed-faas}
    restart: always
    profiles:
      - test-calculate-billing
  
  distributed-faas-billing-service:
    container_name: distributed-faas-billing-service
    build:
      context: ../../../
      dockerfile: services/billing-service/Dockerfile
    ports:
      - 50056:50050
    environment:
      PORT: 50050
      BILLING_MONGO_URI: mongodb://admin:password@distributed-faas-mongo:27017/?replicaSet=rs0&directConnection=true
      BILLING_MONGO_DATABASE: billing-db
      BILLING_MONGO_COLLECTION: billing
    networks:
      - ${GLOBAL_NETWORK:-distributed-faas}
    restart: always
    profiles:
      - test-calculate-billing

  distributed-faas-billing-cron-service:
    container_name: distributed-faas-billing-cron-service
    build:
      context: ../../../
      dockerfile: services/billing-cron-service/Dockerfile
    environment:
      CRON_MONGO_URI: mongodb://admin:password@distributed-faas-mongo:27017/?replicaSet=rs0&directConnection=true
      CRON_MONGO_DATABASE: cron-db
      CRON_MONGO_COLLECTION: cron
      CRON_INTERVAL_IN_SEC: 3
    networks:
      - ${GLOBAL_NETWORK:-distributed-faas}
    restart: always
    profiles:
      - test-generate-billing

  